services:
  woo_maria_db:
    build: ./mariadb
    container_name: woo_maria_db
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      MARIADB_ROOT_PASSWORD: foobar

  woo_wordpress:
    build: ./wordpress
    container_name: woo_wordpress
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_HOST: woo_maria_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WP_ENVIRONMENT_TYPE: local
